### ISSUE TITLE
The model not recording incoming data.

### ISSUE THREAD

**Issue by FredsTechVerse** [FredzTech/Form_Handling-React-Back-End-#1]
I was able to create a model for mongodb in express.The post method works as it creates a document in MongoDB Atlas.But the document only has an Id property.I do not know why it is refusing to pick up the name and the email property that I am sending alongside the post request.Kindly assist.

**Comment by FredzTech** [comment]
The main error was in creating the json post method with axios.It should receive three parameters with the third optional.
ie(url,body,additional_info).

**Comment by FredsTechVerse** [comment]
The main error was in creating the json post method with axios.It should receive three parameters with the third optional.
ie(url,body,additional_info).
